config/routes.rb
Mmlodging::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'


  #admin routes
  namespace :admin do
    root "dashboard#index"
    get "search" => "dashboard#search", as: :search
    get "notifications" => "activities#index", as: :activities
    get "places" => "places#index", as: :all_places
    get "hotels" => "hotels#index", as: :all_hotels
    get "properties" => "properties#index", as: :all_properties
    get "refunds" => "user_refunds#index", as: :all_refunds
    post "confirm_refund" => "user_refunds#confirm_refund", as: :confirm_refund
    #checkouts
    get "checkouts" => "checkouts#index", as: :all_checkouts
    post "checkouts/confirm/:id" => "checkouts#confirm", as: :confirm_checkout

    post "new_facility" => "properties#new_facility", as: :new_facility

    post "page/update" => 'page#update', as: :update_page
    get "page/cancellation" => "page#cancellation", as: :cancellation_page
    get "page/terms" => "page#terms", as: :terms_page
    get "page/story" => "page#story", as: :story_page
    get "page/privacy" => "page#privacy", as: :privacy_page
    get "page/homepage" => "page#homepage", as: :homepage

    resources :faqs do
      member do
        get "child"
        post "child" => "faqs#create_child"
        get "new_child"
      end
    end

    resources :checkouts do
      get "detail"
      collection do
        get "user/:user_id" => "checkouts#user", as: :user
      end
    end

    resources :homeimgs do
      member do
        patch "active"
      end
    end

    resources :blogs do
      member do
        delete "destroy_comment/:comment_id" => "blogs#destroy_comment", as: :destroy_comment
      end
    end
    resources :users
    resources :cities do
      resources :properties do
        post "published"
        post "deals"
        resources :rooms do
          resources :pricings do
            collection do
              get "no_room" => 'pricings#no_room', as: :no_room
            end
          end
        end
      end
      resources :places
    end
  end
  #dashboard user routes
  namespace :dashboard do
    root "users#index"
    get "checkouts/:property_id" => "users#checkouts", :as => :checkouts
    get "checkouts/:property_id/detail/:id" => "users#checkout_detail", :as => :checkout_detail
    post "checkouts/cancel/:id" => "users#cancel", :as => :cancel
    get "checkouts/detail/:id" => "users#details", :as => :details
    get "checkouts/change_date/:id" => "users#change", :as => :change_date
    post "checkouts/change_date/:id" => "users#change_date", :as => :change_date_update
    get "checkouts/detail/:id/cancel" => "users#confirm_cancel", :as => :confirm_cancel
    get "checkouts/check_available/:id" => "users#check_available", :as => :check_available
    post "checkouts/payment/:id" => "users#payment", :as => :payment
    resources :change_bookings
  end

  #page static
  get "privacy" => "homepages#privacy", :as => :privacy
  get "story" => "homepages#story", :as => :story
  get "terms" => "homepages#terms", :as => :terms
  get "cancellation" => "homepages#cancellation", :as => :cancellation
  get "faq" => "homepages#faq", :as => :faq

  #properties and review
  resources :properties, only: :show do
    get "map"
    get "reviews"
    resources :comments, only: [:create, :destroy]
  end

  #cities
  get "cities_info" => "cities#cities_info", :as => :cities_info
  resources :cities, :only => :show do
    resources :places, :only => [:index, :show]
    member do
      get "map"
    end
  end

  #blogs routes
  get "blog" => "blogs#index", :as => :blogs
  get "blog/:id" => "blogs#show", :as => :blog
  post "blog/:id/comment" => "blog_comments#create", :as => :blog_comment
  get "blog/tags/:tag" => "blogs#tags", :as => :tags_blog

  # Checkouts Controller
  post "/checkouts" => "checkouts#create", :as => :checkouts
  get "/checkouts/success" => "checkouts#success", :as => :checkouts_success
  get "/checkouts/express" => "checkouts#express", :as => :checkouts_express
  get "/checkouts/new" => "checkouts#new", :as => :new_checkout
  post "/checkouts/new" => "checkouts#new"

  #search
  get '/map_search', to: 'search#map_search'
  get "search" => "search#index", :as => :search_index

  #to mailer contact
  get "contacts/new"
  post "/contacts", to: "contacts#create"

  
  devise_for :users,
    :controllers => {
      :registrations => "registrations",
      :omniauth_callbacks => 'omniauth',
      :sessions => 'sessions',
      :confirmations => 'confirmations'
    }

  root 'cities#index'
  match "*path", to: "application#record_not_found", via: :all  
end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
  # include Mongoid::Document
  # field :title, type: String
  # field :content, type: String
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :set_homepage, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource param_method: :my_sanitizer

  def faq
    @faqs = Faq.all
  end

  def terms
    @page = Page.where(:name => "terms").first
  end

  def privacy
    @page = Page.where(:name => "privacy").first
  end

  def story
    @page = Page.where(:name => "story").first
  end

  def cancellation
    @page = Page.where(:name => "cancellation").first
  end

  def index
    @homepages = Homepage.all
    @homepage = Homepage.last
  end

  # GET /homepages/1
  # GET /homepages/1.json
  def show
  end

  # GET /homepages/new
  def new
    @homepage = Homepage.new
  end

  # GET /homepages/1/edit
  def edit
  end

  # POST /homepages
  # POST /homepages.json
  def create
    @homepage = Homepage.new(homepage_params)

    respond_to do |format|
      if @homepage.save
        format.html { redirect_to @homepage, notice: 'Homepage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @homepage }
      else
        format.html { render action: 'new' }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homepages/1
  # PATCH/PUT /homepages/1.json
  def update
    respond_to do |format|
      if @homepage.update(homepage_params)
        format.html { redirect_to @homepage, notice: 'Homepage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homepages/1
  # DELETE /homepages/1.json
  def destroy
    @homepage.destroy
    respond_to do |format|
      format.html { redirect_to homepages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homepage
      @homepage = Homepage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homepage_params
      params.require(:homepage).permit(:title, :content)
    end

    def my_sanitizer
      params.require(:homepage).permit(:name)
    end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/_form.html.haml
= form_for @homepage do |f|
  - if @homepage.errors.any?
    #error_explanation
      %h2= "#{pluralize(@homepage.errors.count, "error")} prohibited this homepage from being saved:"
      %ul
        - @homepage.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content, required: "true", :class => "redactor"
  %br
  .actions
    = f.submit 'Save', class: "button disabled"

app/views/homepages/cancellation.html.haml
.content
	.row
		.large-12.medium-12.small-12.columns.margin-from-header
			%h1 Cancellation Policy
			.cancellation
				= @page.content.html_safe

app/views/homepages/edit.html.haml
.content
  .row
    .large-12.medium-12.columns.margin-from-header.security-privacy
      %h1 Editing Homepages box

      = render 'form'
      .clear-both
      %hr
      = link_to 'Back', homepages_path

app/views/homepages/faq.html.haml
.content
	.row
		.large-12.medium-12.small-12.columns.margin-from-header
			%h1 FAQ

			%ul.accordion{"data-accordion" => true}
			- @faqs.where(:parent_id => nil).each do |faq|
				%li.accordion-navigation
					%a
						%h5= faq.name
					.content
						%ol
							- @faqs.where(:parent_id => faq.id).each do |f|
								%li
									= f.name
									.content
										= f.content.html_safe

app/views/homepages/index.html.haml
.content
  .row
    .large-12.medium-12.columns.margin-from-header.security-privacy
      - if @homepages.count > 0
        %p= @homepage.title
        = simple_format(@homepage.content)
        -if user_signed_in?
          -if current_user.has_role?(:admin)
            .clear-both
            %hr
            %td= link_to 'Edit', edit_homepage_path(@homepages)
            %td= link_to 'Destroy', @homepages, :method => :delete, :data => { :confirm => 'Are you sure?' }

      - else
        -if user_signed_in?
          -if current_user.has_role?(:admin)
            %p Now information is unavailable, but you can fill it.
            %br= link_to 'Fill Homepage', new_homepage_path
          - else 
            %p Now information is unavailable
        - else 
          %p Now information is unavailable

app/views/homepages/new.html.haml
.content
  .row
    .large-12.medium-12.columns.margin-from-header.security-privacy
      %h1 Fill Home Page Box

      = render 'form'
      .clear-both
      %hr
      = link_to 'Back', homepages_path

app/views/homepages/privacy.html.haml
.content
	.row
		.large-12.medium-12.small-12.columns.margin-from-header
			%h1 Privacy Policies
			.privacy
				= @page.content.html_safe

app/views/homepages/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @homepage.title
%p
  %b Content:
  = simple_format(@homepage.content)

= link_to 'Edit', edit_homepage_path(@homepage)
\|
= link_to 'Back', homepages_path

app/views/homepages/story.html.haml
.content
	.row
		.large-12.medium-12.small-12.columns.margin-from-header
			%h1 Our Story
			.story
				= @page.content.html_safe

app/views/homepages/terms.html.haml
.content
	.row
		.large-12.medium-12.small-12.columns.margin-from-header
			%h1 Terms and Conditions
			.terms
				= @page.content.html_safe