config/routes.rb
Mmlodging::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'


  #admin routes
  namespace :admin do
    root "dashboard#index"
    get "search" => "dashboard#search", as: :search
    get "notifications" => "activities#index", as: :activities
    get "places" => "places#index", as: :all_places
    get "hotels" => "hotels#index", as: :all_hotels
    get "properties" => "properties#index", as: :all_properties
    get "refunds" => "user_refunds#index", as: :all_refunds
    post "confirm_refund" => "user_refunds#confirm_refund", as: :confirm_refund
    #checkouts
    get "checkouts" => "checkouts#index", as: :all_checkouts
    post "checkouts/confirm/:id" => "checkouts#confirm", as: :confirm_checkout

    post "new_facility" => "properties#new_facility", as: :new_facility

    post "page/update" => 'page#update', as: :update_page
    get "page/cancellation" => "page#cancellation", as: :cancellation_page
    get "page/terms" => "page#terms", as: :terms_page
    get "page/story" => "page#story", as: :story_page
    get "page/privacy" => "page#privacy", as: :privacy_page
    get "page/homepage" => "page#homepage", as: :homepage

    resources :faqs do
      member do
        get "child"
        post "child" => "faqs#create_child"
        get "new_child"
      end
    end

    resources :checkouts do
      get "detail"
      collection do
        get "user/:user_id" => "checkouts#user", as: :user
      end
    end

    resources :homeimgs do
      member do
        patch "active"
      end
    end

    resources :blogs do
      member do
        delete "destroy_comment/:comment_id" => "blogs#destroy_comment", as: :destroy_comment
      end
    end
    resources :users
    resources :cities do
      resources :properties do
        post "published"
        post "deals"
        resources :rooms do
          resources :pricings do
            collection do
              get "no_room" => 'pricings#no_room', as: :no_room
            end
          end
        end
      end
      resources :places
    end
  end
  #dashboard user routes
  namespace :dashboard do
    root "users#index"
    get "checkouts/:property_id" => "users#checkouts", :as => :checkouts
    get "checkouts/:property_id/detail/:id" => "users#checkout_detail", :as => :checkout_detail
    post "checkouts/cancel/:id" => "users#cancel", :as => :cancel
    get "checkouts/detail/:id" => "users#details", :as => :details
    get "checkouts/change_date/:id" => "users#change", :as => :change_date
    post "checkouts/change_date/:id" => "users#change_date", :as => :change_date_update
    get "checkouts/detail/:id/cancel" => "users#confirm_cancel", :as => :confirm_cancel
    get "checkouts/check_available/:id" => "users#check_available", :as => :check_available
    post "checkouts/payment/:id" => "users#payment", :as => :payment
    resources :change_bookings
  end

  #page static
  get "privacy" => "homepages#privacy", :as => :privacy
  get "story" => "homepages#story", :as => :story
  get "terms" => "homepages#terms", :as => :terms
  get "cancellation" => "homepages#cancellation", :as => :cancellation
  get "faq" => "homepages#faq", :as => :faq

  #properties and review
  resources :properties, only: :show do
    get "map"
    get "reviews"
    resources :comments, only: [:create, :destroy]
  end

  #cities
  get "cities_info" => "cities#cities_info", :as => :cities_info
  resources :cities, :only => :show do
    resources :places, :only => [:index, :show]
    member do
      get "map"
    end
  end

  #blogs routes
  get "blog" => "blogs#index", :as => :blogs
  get "blog/:id" => "blogs#show", :as => :blog
  post "blog/:id/comment" => "blog_comments#create", :as => :blog_comment
  get "blog/tags/:tag" => "blogs#tags", :as => :tags_blog

  # Checkouts Controller
  post "/checkouts" => "checkouts#create", :as => :checkouts
  get "/checkouts/success" => "checkouts#success", :as => :checkouts_success
  get "/checkouts/express" => "checkouts#express", :as => :checkouts_express
  get "/checkouts/new" => "checkouts#new", :as => :new_checkout
  post "/checkouts/new" => "checkouts#new"

  #search
  get '/map_search', to: 'search#map_search'
  get "search" => "search#index", :as => :search_index

  #to mailer contact
  get "contacts/new"
  post "/contacts", to: "contacts#create"

  
  devise_for :users,
    :controllers => {
      :registrations => "registrations",
      :omniauth_callbacks => 'omniauth',
      :sessions => 'sessions',
      :confirmations => 'confirmations'
    }

  root 'cities#index'
  match "*path", to: "application#record_not_found", via: :all  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :set_properties

  def index
    if @title.nil?
      @title = {:title => "Search Lodgings", :description => "search lodgings in mmlodging", :keywords => %w(search lodging mmlodging hotel room booking city)}
    end
    @property_types = [["Hostel"], ["Bed and Breakfast"], ["Hotel"], ["Inn"], ["Motel"]]
    @facilities = Facility.where(:facility_type => 'Facility')
    @payments = Facility.where(:facility_type => 'Payment')
    @cities = City.all.map {|city| [city.name, city.slug]}
    @guests = Array(1..15)

    if params[:sort_by_rating] || params[:sort_by_price]
      if params[:sort_by_rating].eql?("desc")
        @properties = @properties.order(:rating => :desc)
      else
        @properties = @properties.order(:rating => :asc)
      end

      if params[:sort_by_price].eql?("desc")
        @properties = @properties.order(:price => :desc)
      else
        @properties = @properties.order(:price => :asc)
      end
    else
      @properties = @properties.order(:created_at => :desc)
    end

    @properties_map = @properties
    @properties = Kaminari.paginate_array(@properties).page(params[:page]).per(5)
  end

  def map_search
    @hash = []
    @properties.map {|p| @hash << {:latlng => [p.lat, p.lng]} }
    @panTo = []
    @properties.map {|p| @panTo << [p.lat, p.lng]}
  end

  private

  def set_properties
    @properties = Property.published.includes(:facilities, :photos)

    min = params[:minimum]
    max = params[:maximum]
    guest = params[:guest]
    from = params[:from]
    to = params[:to]
    city = City.friendly.find(params[:city]) rescue []
    title = params[:title]

    property_type = params[:property_type]
    room_type = params[:room_type]
    facility_type = params[:facility_type]
    payment_type = params[:payment_type]

    sort_by_price = params[:sort_by_rating]
    sort_by_rating = params[:sort_by_price]

    if min && max
      @properties = @properties.prices(min.to_i, max.to_i)
    end

    if guest
      @properties = @properties.where("guests >= ?", guest.to_i)
    end

    if city && !city.blank?
      @title = {:title => "Lodgings in #{city.name}", :description => city.description, :keywords => city.name.split( ) << ["search", "lodgings"]}
      @properties = @properties.where(:city_id => city.id)
    end

    if to && from
      @properties = @properties.ratings(from.to_i, to.to_i)
    end

    if property_type
      @properties = @properties.where("property_type IN(?)", property_type)
    end

    if room_type
      @properties = @properties.where("room_type IN(?)", room_type)
    end
    
    if facility_type
      @properties = @properties.where(:facilities => {:id => facility_type})
    end

    if payment_type
      @properties = @properties.where(:facilities => {:id => payment_type})
    end

    if title
      @properties = @properties.where("title ILIKE ?", "%#{title}%")
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_hotels.html.haml
%table
  %thead
    %tr
      %th Title
      %th Content
      %th in
      %th out
      %th hotel
      %th hotel_id
      %th hotel_rating
      %th
      %th
      %th
  %tbody
    - @hotels.each do |h|
      %tr
        %td= h.title
        %td= h.rating

app/views/search/_result.html.haml
%table
  %thead
    %tr
      %th Title
      %th Rating
  %tbody
    - @rooms.each do |r|
      %tr
        %td= r.type
        %td= r.guest

app/views/search/date.html.haml
%h1 SearchByDate#index
= form_tag(search_date_path, :method => "get", id: "searchform") do
  = date_field_tag :check_in, params[:check_in], placeholder: "Check in..", required: 'true'
  = date_field_tag :check_out, params[:check_out], placeholder: "Check out..", required: 'true'
  = select_tag :city, options_for_select( City.all.collect{ |u| [u.name, u.id] }, params[:city])
  = select_tag :guest, options_for_select( [['1','1'],['2','2'],['3','3']], params[:guest])
  = submit_tag "Filter", :name => nil, id: "go", class: "ct-search-submit"
%h1 REsult
#result
  = render(partial:'result')

app/views/search/index.html.haml
- meta title: @title[:title], description: truncate(strip_tags(@title[:description]), length: 255), keywords: @title[:keywords]
.content
  .row
    .large-12.medium-12.columns
      .large-3.medium-3.columns
        .content_filters.margin-from-header
          = form_tag(search_index_path, :method => "get", id: "searchform_room", name: "form1") do
            .content_search-hostels
              %h5 Search Lodgings
              = text_field_tag :title, params[:title], placeholder: "Lodging Name"
              .mozfix-select
                = select_tag(:city, options_for_select(@cities, params[:city]), prompt: "Select City")
              .check_in
                = text_field_tag :check_in, params[:check_in], placeholder: "Check in..", id: 'from'
              .check_out
                = text_field_tag :check_out, params[:check_out], placeholder: "Check out..", id: 'to'
              .mozfix-select
              = select_tag :guest, options_for_select(@guests, params[:guest]), :prompt => "Guests"
              = submit_tag "Search", :name => nil, id: "go", class: "visible-for-medium-only button expand radius tiny yellow", onclick: "validatecal(document.form1.check_in, document.form1.check_out)"
            .content_filter-results
              %h5 Filter Results
              .accordion-block
                %h3 price (USD)
                .accordion1
                  .slider-line
                    #slider-range1
                    %label{for: "amount1"} Range:
                    %input#amount1/
                    .hide= number_field_tag :minimum, params[:minimum], placeholder: "From..", required: 'true', id: 'amount201', class: "display-none"
                    .hide= number_field_tag :maximum, params[:maximum], placeholder: "To", required: 'true', id: 'amount202'
                %hr
                %h3 Rating
                .accordion1
                  %label From:
                  .filter_rating_from{"data-rating" => (params[:from] || 0)}
                  = hidden_field_tag :from, (params[:from] || 0), id: "from_rating"
                  %label To:
                  .filter_rating_to{"data-rating" => (params[:to] || 100)}
                  = hidden_field_tag :to, (params[:to] || 100), id: "to_rating"
                %hr
                %h3 Property type
                .accordion1
                  - @property_types.each do |type|
                    - type = type.shift.strip
                    - if params[:property_type] && params[:property_type].include?(type)
                      - show = true
                    - else
                      - show = false
                    .checkbox-block
                      %label.checkbox
                        = check_box_tag "property_type[]", type, show
                        %span
                      %label
                        = type
                    .clear-both
                %hr
                %h3 Payment type
                .accordion1
                  - @payments.each do |payment|
                    - if params[:payment_type] && params[:payment_type].include?(payment.id.to_s)
                      - show = true
                    - else
                      - show = false
                    .checkbox-block
                      %label.checkbox
                        = check_box_tag "payment_type[]", payment.id, show
                        %span
                      %label
                        = payment.facility_name
                    .clear-both
                %hr  
              = submit_tag("Search", class: "button expand radius tiny yellow")
              = button_tag("Clear All", type: :reset, class: "button expand radius tiny orange")
      .site-overlay
      .large-9.medium-12.columns.padding-lr-0#container
        .margin-from-header.content_finder-hostels
          .menu-btn &#9776; Search
          .content_finder-hostels_header
            - if @properties.present?
              .content_finder-hostels_header_show-map= link_to 'Show Map', map_search_path(params)
            .clear-both
            - if @properties.present?
              %hr
              %dl.sub-nav
                %br
                %dt Sort by:
                - if params[:sort_by_rating] == 'desc'
                  %dd.active
                    = link_to search_index_path(params.except(:sort_by_rating, :sort_by_price).merge(sort_by_rating: "asc")) do
                      %i.fa.fa-long-arrow-up
                      Rating
                - elsif params[:sort_by_rating] == 'asc'
                  %dd.active
                    = link_to search_index_path(params.except(:sort_by_rating, :sort_by_price).merge(sort_by_rating: "desc")) do
                      %i.fa.fa-long-arrow-down
                      Rating
                - else
                  %dd
                    = link_to search_index_path(params.except(:sort_by_rating, :sort_by_price).merge(sort_by_rating: "desc")) do
                      Rating
                - if params[:sort_by_price] == 'desc'
                  %dd.active
                    = link_to search_index_path(params.except(:sort_by_rating, :sort_by_price).merge(sort_by_price: "asc")) do
                      %i.fa.fa-long-arrow-up
                      Price
                - elsif params[:sort_by_price] == 'asc'
                  %dd.active
                    = link_to search_index_path(params.except(:sort_by_rating, :sort_by_price).merge(sort_by_price: "desc")) do
                      %i.fa.fa-long-arrow-down
                      Price
                - else
                  %dd
                    = link_to "Price", search_index_path(params.except(:sort_by_rating, :sort_by_price).merge(sort_by_price: "desc"))
            
                %p
          - @properties.each do |property|
            .content_finder-hostels_inner
              .large-4.medium-4.small-12.columns.padding-lr-0.content_finder-hostels_inner_img
                %a
                  - if property.photos.empty?
                    = image_tag('/assets/default.png', :class => "reload")
                  - else
                    = image_tag(property.photos.first.image, :class => "reload")
              .large-8.medium-8.small-12.columns.padding-lr-0.content_finder-hostels_inner_text-rating
                .large-7.medium-12.small-12columns.padding-lr-0.content_finder-hostels_inner_text.columns
                  - if params[:check_in] || params[:check_out]
                    %h5= link_to property.title, property_path(property, :check_in => params[:check_in], :check_out => params[:check_out], :guest => params[:guest])
                  - else
                    %h5=link_to property.title, property_path(property)
                  %p
                    = truncate(property.content, length: 150, escape: false)
                  %p
                    = link_to "Continue", property_path(property)
                .large-5.medium-12.columns.padding-lr-0.content_finder-hostels_inner_rating
                  .content_finder-hostels_inner_rating_header
                    %div{style: "width: 100px; margin: 0 auto;"}
                      .rating_star{"data-rating" => property.rating}
                    .clear-both
                  .content_finder-hostels_inner_rating_prices
                    %p.content_finder-hostels_inner_rating_prices_price
                      Price/Night
                      %span= number_to_currency(property.price)
                    %hr
                    - if params[:check_out] || params[:check_in] || params[:guest]
                      = link_to "BOOK NOW", property_path(property, :check_in => params[:check_in], :check_out => params[:check_out], :guest => params[:guest]), class:'button radius expand tiny orange'
                    - else
                      = link_to "BOOK NOW", property_path(property), class:'button radius expand tiny orange'
              .clear-both
          - if @properties.present?
            = paginate @properties
          -else
            %h4.text-center Hotels with this attributes don't exist

app/views/search/map_hotels.html.haml
.content
  .row
    .large-12.medium-12.small-12.columns.margin-from-header.hotel
      .hotel_header
        .large-4.medium-4.small-12.columns.padding-lr-0
          %h3= @hotel.title
          %p= @hotel.distance_from_city_center
        .large-8.medium-8.small-12.columns.padding-lr-0
          %dl.tabs{"data-tab" => ""}
            %dd.active
              %a{href: "#panel2-1"} Overview
            %dd
              %a{href: "#panel2-2"} Map
            %dd
              %a{href: "#panel2-3"} Reviews
          = link_to 'Back to search', search_index_path, class: "button-full-width-yellow"
      .hotel_inside-pages
        .tabs-content          
          #panel2-2.content.large-12.medium-12.small-12.columns.map-hotel
            .large-12.medium-12.small-12.columns.padding-lr-0
              .map-hotel_map-block
                = render "partial/map"
              .map-hotel_text
                %h4 Located Near
                %p Skate alongside the lake and enjoy the spectacular city views at Harbourfront, or go out for a live show and some drinks on Queen West. We're in the middle of it all! Stroll to many of Toronto's top destinations, including the CN Tower, King West, the Theatre District, and Chinatown. All are within an easy 5-10 minute walk. Public transit is super convenient: two TTC streetcar lines (King and Spadina) run 100 metres from our front door, with direct service to the subway.

app/views/search/map_search.html.haml
.content
  .row
    .large-12.medium-12.small-12.columns.margin-from-header.hotel
      .hotel_header
        .large-4.medium-4.small-12.columns.padding-lr-0
          %h3
          %p
        .large-8.medium-8.small-12.columns.padding-lr-0
          = link_to 'Back to search', search_index_path, class: "button-full-width-yellow"
      .hotel_inside-pages
        .tabs-content          
          #panel2-2.content.large-12.medium-12.small-12.columns.map-hotel.active
            .large-12.medium-12.small-12.columns.padding-lr-0
              .map-hotel_map-block
                = render "partial/map"
              .map-hotel_text
              -#
                %h4 Located Near
                %p Skate alongside the lake and enjoy the spectacular city views at Harbourfront, or go out for a live show and some drinks on Queen West. We're in the middle of it all! Stroll to many of Toronto's top destinations, including the CN Tower, King West, the Theatre District, and Chinatown. All are within an easy 5-10 minute walk. Public transit is super convenient: two TTC streetcar lines (King and Spadina) run 100 metres from our front door, with direct service to the subway.