config/routes.rb
Mmlodging::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'


  #admin routes
  namespace :admin do
    root "dashboard#index"
    get "search" => "dashboard#search", as: :search
    get "notifications" => "activities#index", as: :activities
    get "places" => "places#index", as: :all_places
    get "hotels" => "hotels#index", as: :all_hotels
    get "properties" => "properties#index", as: :all_properties
    get "refunds" => "user_refunds#index", as: :all_refunds
    post "confirm_refund" => "user_refunds#confirm_refund", as: :confirm_refund
    #checkouts
    get "checkouts" => "checkouts#index", as: :all_checkouts
    post "checkouts/confirm/:id" => "checkouts#confirm", as: :confirm_checkout

    post "new_facility" => "properties#new_facility", as: :new_facility

    post "page/update" => 'page#update', as: :update_page
    get "page/cancellation" => "page#cancellation", as: :cancellation_page
    get "page/terms" => "page#terms", as: :terms_page
    get "page/story" => "page#story", as: :story_page
    get "page/privacy" => "page#privacy", as: :privacy_page
    get "page/homepage" => "page#homepage", as: :homepage

    resources :faqs do
      member do
        get "child"
        post "child" => "faqs#create_child"
        get "new_child"
      end
    end

    resources :checkouts do
      get "detail"
      collection do
        get "user/:user_id" => "checkouts#user", as: :user
      end
    end

    resources :homeimgs do
      member do
        patch "active"
      end
    end

    resources :blogs do
      member do
        delete "destroy_comment/:comment_id" => "blogs#destroy_comment", as: :destroy_comment
      end
    end
    resources :users
    resources :cities do
      resources :properties do
        post "published"
        post "deals"
        resources :rooms do
          resources :pricings do
            collection do
              get "no_room" => 'pricings#no_room', as: :no_room
            end
          end
        end
      end
      resources :places
    end
  end
  #dashboard user routes
  namespace :dashboard do
    root "users#index"
    get "checkouts/:property_id" => "users#checkouts", :as => :checkouts
    get "checkouts/:property_id/detail/:id" => "users#checkout_detail", :as => :checkout_detail
    post "checkouts/cancel/:id" => "users#cancel", :as => :cancel
    get "checkouts/detail/:id" => "users#details", :as => :details
    get "checkouts/change_date/:id" => "users#change", :as => :change_date
    post "checkouts/change_date/:id" => "users#change_date", :as => :change_date_update
    get "checkouts/detail/:id/cancel" => "users#confirm_cancel", :as => :confirm_cancel
    get "checkouts/check_available/:id" => "users#check_available", :as => :check_available
    post "checkouts/payment/:id" => "users#payment", :as => :payment
    resources :change_bookings
  end

  #page static
  get "privacy" => "homepages#privacy", :as => :privacy
  get "story" => "homepages#story", :as => :story
  get "terms" => "homepages#terms", :as => :terms
  get "cancellation" => "homepages#cancellation", :as => :cancellation
  get "faq" => "homepages#faq", :as => :faq

  #properties and review
  resources :properties, only: :show do
    get "map"
    get "reviews"
    resources :comments, only: [:create, :destroy]
  end

  #cities
  get "cities_info" => "cities#cities_info", :as => :cities_info
  resources :cities, :only => :show do
    resources :places, :only => [:index, :show]
    member do
      get "map"
    end
  end

  #blogs routes
  get "blog" => "blogs#index", :as => :blogs
  get "blog/:id" => "blogs#show", :as => :blog
  post "blog/:id/comment" => "blog_comments#create", :as => :blog_comment
  get "blog/tags/:tag" => "blogs#tags", :as => :tags_blog

  # Checkouts Controller
  post "/checkouts" => "checkouts#create", :as => :checkouts
  get "/checkouts/success" => "checkouts#success", :as => :checkouts_success
  get "/checkouts/express" => "checkouts#express", :as => :checkouts_express
  get "/checkouts/new" => "checkouts#new", :as => :new_checkout
  post "/checkouts/new" => "checkouts#new"

  #search
  get '/map_search', to: 'search#map_search'
  get "search" => "search#index", :as => :search_index

  #to mailer contact
  get "contacts/new"
  post "/contacts", to: "contacts#create"

  
  devise_for :users,
    :controllers => {
      :registrations => "registrations",
      :omniauth_callbacks => 'omniauth',
      :sessions => 'sessions',
      :confirmations => 'confirmations'
    }

  root 'cities#index'
  match "*path", to: "application#record_not_found", via: :all  
end

app/models/place.rb
class Place < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :placeimg, PlaceimgUploader

  belongs_to :city
  
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < AdminController
  before_action :check_role
	before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :set_city, only: [:show, :edit,:create, :update, :destroy]
  load_and_authorize_resource param_method: :my_sanitizer

  # GET /places
  # GET /places.json
  def index
    @cities = City.all
    if params[:city_id]
      set_city
      @places = @city.places
    else
      @places = Place.all
    end

    @hash = []
    @places.map {|p| @hash << {:latlng => [p.lat, p.lng]} }
    @panTo = []
    @places.map {|p| @panTo << [p.lat, p.lng]}

  end

  # GET /places/1
  # GET /places/1.json
  def show
    @cities = City.all
    @places = Place.where(:city_id => params[:city_id]).all

    @hash = Gmaps4rails.build_markers(@place) do |user, marker|
      marker.lat user.lat
      marker.lng user.lng
    end
  end

  # GET /places/new
  def new
    @city = City.friendly.find(params[:city_id])
    @place = @city.places.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create

    @city = City.friendly.find(params[:city_id])
    @place = @city.places.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to admin_city_places_url(@city), notice: {:type => 'success', :msg => "Place was successfully created."} }
        format.json { render action: 'show', status: :created, location: [@city,@place] }
      else
        format.html { render action: 'new' }
        format.json { render json: [@city,@place].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params.merge(city_id: @city.id))
        format.html { redirect_to admin_city_places_url(@city), notice: {:type => 'success', :msg => "Place was successfully updated."} }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: [@city,@place].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to admin_city_places_url(@city), notice: {:type => 'success', :msg => "Place was successfully deleted."} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.friendly.find(params[:id])
    end

    def set_city
      @city = City.friendly.find(params[:city_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :content, :city_id, :address, :town, :state, :country, :placeimg, :lat, :lng)
    end

    def my_sanitizer
      params.require(:place).permit(:name)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :set_city, only: [:index, :show, :edit,:create, :update, :destroy]
  load_and_authorize_resource param_method: :my_sanitizer

  # GET /places
  # GET /places.json
  def index
    @places = @city.places
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @cities = City.all
    @places = Place.where(:city_id => params[:city_id]).all

    @hash = [{:latlng => [@place.lat, @place.lng], :popup => @place.title}]
    @panTo = [@place.lat, @place.lng]
  end

  # GET /places/new
  def new
    @city = City.friendly.find(params[:city_id])
    @place = @city.places.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create

    @city = City.friendly.find(params[:city_id])
    @place = @city.places.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to [@city,@place], notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@city,@place] }
      else
        format.html { render action: 'new' }
        format.json { render json: [@city,@place].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to [@city,@place], notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: [@city,@place].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to city_places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.friendly.find(params[:id])
    end

    def set_city
      @city = City.friendly.find(params[:city_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :content, :city_id, :address, :town, :state, :country, :placeimg, :lat, :lng)
    end

    def my_sanitizer
      params.require(:place).permit(:name)
    end
end

app/helpers/admin/places_helper.rb
module Admin::PlacesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admin/places/_form.html.haml
= simple_form_for([:admin, @city, @place], :html => {:id => "form-place"}) do |f|
  .col-md-8
    .portlet.light
      .portlet-title
        .caption.caption-md
          %i.icon-bar-chart.theme-font.hide
          %span.caption-subject.theme-font.bold.uppercase Description Place
      .portlet-body
        = f.input :lat, :as => :hidden, :input_html => {"data-geo" => "lat"}
        = f.input :lng, :as => :hidden, :input_html => {"data-geo" => "lng"}
      
        = f.input :address, :input_html => {:class => 'form-control'}
        = f.input :title, :input_html => {:class => 'form-control'}
        = f.input :town, :input_html => {:class => 'form-control'}
        = f.input :country, :input_html => {:class => 'form-control'}
        = f.input :state, :input_html => {:class => 'form-control'}
        = f.input :content, :as => :ckeditor, :input_html => {:ckeditor => {:toolbar => 'simple'}, :class => 'form-control'}
        = f.input :placeimg, :as => :file
  .col-md-4
    / BEGIN REGIONAL STATS PORTLET
    .portlet.light
      .portlet-title
        .caption.caption-md
          %i.icon-bar-chart.theme-font.hide
          %span.caption-subject.theme-font.bold.uppercase Map Place
      .portlet-body
        #maps{style: "height:400px"}
    .portlet.light
      .portlet-body
        = link_to "Back", admin_root_path, :class => 'btn green'
        = f.submit "Save", :class => 'btn green'

- content_for :scripts do
  %script{:src => "http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"}
  = javascript_include_tag "jquery.geocomplete.min"
  - if params[:action].eql?("new")
    :javascript
      $("#place_address").geocomplete({
        map: "#maps",
        details: "#form-place",
        detailsAttribute: "data-geo",
        location: "#{@city.lat}, #{@city.lng}",
        markerOptions: {
          draggable: true
        }
      });
      $("#place_address").bind("geocode:dragged", function(event, latLng){
        $("#place_lat").val(latLng.lat());
        $("#place_lng").val(latLng.lng());
      });
  
  - else
    :javascript
      $("#place_address").geocomplete({
        map: "#maps",
        details: "#form-place",
        detailsAttribute: "data-geo",
        location: "#{@place.lat}, #{@place.lng}",
        markerOptions: {
          draggable: true
        }
      });
      $("#place_address").bind("geocode:dragged", function(event, latLng){
        $("#place_lat").val(latLng.lat());
        $("#place_lng").val(latLng.lng());
      });

app/views/admin/places/edit.html.haml
- meta title: "Edit #{@place.title}"
.page-head
  .container
    .page-title
      %h1= "New Place for #{@city.name}"
.page-content
  .container
    - breadcrumb :edit_place, @place
    = render("layouts/breadcrumbs")
    .row= render "form"

app/views/admin/places/index.html.haml
- meta title: "Manage Places"
.page-head
  .container
    .page-title
      %h1
        - if @city
          = "All Places in #{@city.name}"
        - else
          = "All Places"
.page-content
  .container
    - breadcrumb :places
    = render("layouts/breadcrumbs")
    .row
      .col-md-12.col-sm-12
        / BEGIN REGIONAL STATS PORTLET
        .portlet.light
          .portlet-title
            .caption.caption-md
              %i.icon-bar-chart.theme-font.hide
              %span.caption-subject.theme-font.bold.uppercase Places
            .actions
              .btn-group
                %a.btn.btn-circle.btn-default{:href => "javascript:;", "data-toggle" => "dropdown", "aria-expanded" => "false"}
                  %i.fa.fa-plus
                  New Place
                %ul.dropdown-menu.pull-right
                  - @cities.each do |city|
                    %li
                      = link_to city.name, new_admin_city_place_path(city)
          .portlet-body
            %table.table.table-hover
              %thead
                %tr
                  %th Place Name
                  %th{:colspan => 3}
              %tbody
                - @places.each do |place|
                  %tr
                    %td= place.title
                    %td= link_to 'Show', [@city || place.city, place], :class => 'btn btn-sm btn-success'
                    %td= link_to 'Edit', edit_admin_city_place_path(@city || place.city, place), :class => 'btn btn-info btn-sm'
                    %td= link_to 'Destroy', [:admin, @city || place.city, place], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-sm btn-danger'
    - unless @places.blank?
      = render "layouts/map"
-#
  .content
  .row
    .large-12.medium-12.small-12.columns.margin-from-header
      %h1= 'Listing places in ' + @city.name
      %br
      - if @places.size > 0
        %table.w100
          %tr
            %th Title
            %th
            %th
            %th

          - @places.each do |place|
            %tr
              %td= place.title
              %td= link_to 'Show', [@city, place]
              %td= link_to 'Edit', edit_admin_city_place_path(@city,place)
              %td= link_to 'Destroy', [:admin, @city,place], :method => :delete, :data => { :confirm => 'Are you sure?' }
      - else
        %p You don't have any places in this city

      %br
      = link_to 'New Place', new_admin_city_place_path, class: "button"
      %br
      %hr
      = link_to 'Back', admin_root_path
      = render(partial:'partial/map')

app/views/admin/places/new.html.haml
- meta title: "New Place"
.page-head
  .container
    .page-title
      %h1= "New Place for #{@city.name}"
.page-content
  .container
    - breadcrumb :new_place, @city
    = render("layouts/breadcrumbs")
    .row= render "form"

app/views/admin/places/show.html.haml
- meta title: "Detail #{@place.title}"
.content
  .row.city-guides-guides-map
    .large-12.medium-12.small-12.columns.margin-from-header
      .large-12.medium-12.small-12.columns.padding-lr-0.subnav-select
        %dl.tabs.sub-nav
          %dd
            =link_to 'City Guides', [@city, BlogCategory.first]
          %dd.active
            %a{href: "#panel4-2"} Map
          %dd
            =link_to 'Blog', blogs_cat_path(@city, BlogCategory.first)
        %a.button.dropdown.wiching.right{"data-dropdown" => "drop1", href: "#"} Which city?
        %br/
        %ul#drop1.f-dropdown{"data-dropdown-content" => ""}
          - @cities.each do |city|
            %li
              = link_to city.name, [city, BlogCategory.first]
    .tabs-content
      #panel4-2.content.active
        .large-12.medium-12.small-12.columns
          %h3= @city.name
        .large-8.medium-7.small-12.columns
          .city-guides-guides-map_main-img
            %a
              -#= image_tag @city.cityimg_url() if @city.cityimg?
              = render "partial/map"
        .large-3.large-offset-1.medium-4.medium-offset-1.small-12.columns.content_categories_block
          .content_categories
            %h4 Popular City Guides
            - @cities.each do |city|
              =link_to city.name, [city, BlogCategory.first]
        .large-12.medium-12.small-12.columns.padding-lr-0
          .large-12.medium-12.small-12.columns
            %h5= @place.title
            %p= simple_format(@place.content)
            .guides-maps-inside

              - @places.each do |place|
                .guides-maps-inside_block
                  = link_to place.title, [@city, place]
              .clear-both
              %hr
              -#= paginate @places