config/routes.rb
Mmlodging::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'


  #admin routes
  namespace :admin do
    root "dashboard#index"
    get "search" => "dashboard#search", as: :search
    get "notifications" => "activities#index", as: :activities
    get "places" => "places#index", as: :all_places
    get "hotels" => "hotels#index", as: :all_hotels
    get "properties" => "properties#index", as: :all_properties
    get "refunds" => "user_refunds#index", as: :all_refunds
    post "confirm_refund" => "user_refunds#confirm_refund", as: :confirm_refund
    #checkouts
    get "checkouts" => "checkouts#index", as: :all_checkouts
    post "checkouts/confirm/:id" => "checkouts#confirm", as: :confirm_checkout

    post "new_facility" => "properties#new_facility", as: :new_facility

    post "page/update" => 'page#update', as: :update_page
    get "page/cancellation" => "page#cancellation", as: :cancellation_page
    get "page/terms" => "page#terms", as: :terms_page
    get "page/story" => "page#story", as: :story_page
    get "page/privacy" => "page#privacy", as: :privacy_page
    get "page/homepage" => "page#homepage", as: :homepage

    resources :faqs do
      member do
        get "child"
        post "child" => "faqs#create_child"
        get "new_child"
      end
    end

    resources :checkouts do
      get "detail"
      collection do
        get "user/:user_id" => "checkouts#user", as: :user
      end
    end

    resources :homeimgs do
      member do
        patch "active"
      end
    end

    resources :blogs do
      member do
        delete "destroy_comment/:comment_id" => "blogs#destroy_comment", as: :destroy_comment
      end
    end
    resources :users
    resources :cities do
      resources :properties do
        post "published"
        post "deals"
        resources :rooms do
          resources :pricings do
            collection do
              get "no_room" => 'pricings#no_room', as: :no_room
            end
          end
        end
      end
      resources :places
    end
  end
  #dashboard user routes
  namespace :dashboard do
    root "users#index"
    get "checkouts/:property_id" => "users#checkouts", :as => :checkouts
    get "checkouts/:property_id/detail/:id" => "users#checkout_detail", :as => :checkout_detail
    post "checkouts/cancel/:id" => "users#cancel", :as => :cancel
    get "checkouts/detail/:id" => "users#details", :as => :details
    get "checkouts/change_date/:id" => "users#change", :as => :change_date
    post "checkouts/change_date/:id" => "users#change_date", :as => :change_date_update
    get "checkouts/detail/:id/cancel" => "users#confirm_cancel", :as => :confirm_cancel
    get "checkouts/check_available/:id" => "users#check_available", :as => :check_available
    post "checkouts/payment/:id" => "users#payment", :as => :payment
    resources :change_bookings
  end

  #page static
  get "privacy" => "homepages#privacy", :as => :privacy
  get "story" => "homepages#story", :as => :story
  get "terms" => "homepages#terms", :as => :terms
  get "cancellation" => "homepages#cancellation", :as => :cancellation
  get "faq" => "homepages#faq", :as => :faq

  #properties and review
  resources :properties, only: :show do
    get "map"
    get "reviews"
    resources :comments, only: [:create, :destroy]
  end

  #cities
  get "cities_info" => "cities#cities_info", :as => :cities_info
  resources :cities, :only => :show do
    resources :places, :only => [:index, :show]
    member do
      get "map"
    end
  end

  #blogs routes
  get "blog" => "blogs#index", :as => :blogs
  get "blog/:id" => "blogs#show", :as => :blog
  post "blog/:id/comment" => "blog_comments#create", :as => :blog_comment
  get "blog/tags/:tag" => "blogs#tags", :as => :tags_blog

  # Checkouts Controller
  post "/checkouts" => "checkouts#create", :as => :checkouts
  get "/checkouts/success" => "checkouts#success", :as => :checkouts_success
  get "/checkouts/express" => "checkouts#express", :as => :checkouts_express
  get "/checkouts/new" => "checkouts#new", :as => :new_checkout
  post "/checkouts/new" => "checkouts#new"

  #search
  get '/map_search', to: 'search#map_search'
  get "search" => "search#index", :as => :search_index

  #to mailer contact
  get "contacts/new"
  post "/contacts", to: "contacts#create"

  
  devise_for :users,
    :controllers => {
      :registrations => "registrations",
      :omniauth_callbacks => 'omniauth',
      :sessions => 'sessions',
      :confirmations => 'confirmations'
    }

  root 'cities#index'
  match "*path", to: "application#record_not_found", via: :all  
end

app/views/contact_us/_style.html.haml
:css
	table{
		width: 100%;
		border: solid 1px #DDD;
		margin-bottom: 1.25rem;
	}
	table thead{
		background: #F5F5F5;
	}
	table tr:nth-of-type(even){
		background: #F9F9F9;
	}
	.text-right{
		text-align: right !important;
	}

app/views/contact_us/change.html.haml
%html
  %head
    %meta{:charset => "utf-8"}
      %title= "Your Booking Changed}"
      %link{:href => "http://fonts.googleapis.com/css?family=Varela+Round", :rel => "stylesheet", :type => "text/css"}
  %body{:style => "font-family: 'Varela Round', sans-serif; background-color:#f0f2ea; margin:0; padding:0; color:#333333;"}
    %table{:bgcolor => "#f0f2ea", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
      %tbody
        %tr
          %td{:style => "padding:40px 0;"}
            %table{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "800"}
              %tbody
                %tr
                  %td
                    = link_to root_url, :style => 'display:block; width:800px; margin:0 auto 30px;' do
                      = image_tag("voucher/logo.png", :alt => "mmlodging", :style => "display:block; border:0; margin:0;", :width => "350")
                    %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                      %tbody
                        %tr
                          %td{:height => "4", :width => "4"}
                            %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                          %td{:bgcolor => "#FFFFFF", :colspan => "3", :rowspan => "3", :style => "padding:0 0 30px;"}
                            %p{:style => "margin: 30px 30px 10px; text-align:left; font-size:24px; line-height:30px; font-weight:bold; color:rgb(81, 163, 231);"}
                              = "Dear #{@checkout.first_name} #{@checkout.last_name},"
                            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :style => "margin-bottom: 15px", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td{:width => "30"}
                                    %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                            %p{:style => "margin:0; border-top:2px solid #e5e5e5; font-size:5px; line-height:5px; margin:0 30px 29px;"} &nbsp;
                            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      = "Your booking with Booking ID #{@checkout.booking_id}, has been changed and confirmed."
                                %tr{:valign => "top"}
                                  %td{:align => "center"}
                                    = link_to "View", dashboard_details_path(@checkout.id), :style => " background: rgb(81, 163, 231); color: #ffffff; border: none; padding: 5px 15px; margin:0 0 30px 0; font-size:14px; font-weight: bold; line-height: 30px; text-decoration:none; width:190px; display:block;"
                                %tr{:valign => "top"}
                                  %td
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      Kind Regard,
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      MMLodging
                                    = image_tag("voucher/footer.png", :class => 'image img-footer', :height => "200", :src => "footer.png", :style => "margin-bottom: -50px margin-left: 0px", :width => "800")

app/views/contact_us/confirm_order_admin.html.haml
%p
	Dear
	= @checkout.first_name
	= ","
%p
	Your rooms with type:
%ol
	- @rooms.each do |room|
		%li= room.title
%p Already confirmed
%br
%p
	Regards
	MMLodging Team

app/views/contact_us/create_hotel_admin.text.erb
Hotel was create!
Name: <%= @hotel.title %>
City: <%= @hotel.city.name %>
User: <%= @current_user.email %>

app/views/contact_us/destroy_hotel_user.text.erb
Dear Valued Partner, 
We have received your request to delete your hotel from our site. Your hotel has been 
successfully removed from our site. 
 We are sorry to see you go! Please do not hesitate to return in the future. We will 
welcome you back with open arms. 
Sincerely, 
MMLodging 

app/views/contact_us/send_review.html.haml
%html
  %head
    %meta{:charset => "utf-8"}
      %title= "Review #{@checkout.property.title}"
      %link{:href => "http://fonts.googleapis.com/css?family=Varela+Round", :rel => "stylesheet", :type => "text/css"}
  %body{:style => "font-family: 'Varela Round', sans-serif; background-color:#f0f2ea; margin:0; padding:0; color:#333333;"}
    %table{:bgcolor => "#f0f2ea", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
      %tbody
        %tr
          %td{:style => "padding:40px 0;"}
            %table{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "800"}
              %tbody
                %tr
                  %td
                    = link_to root_url, :style => 'display:block; width:800px; margin:0 auto 30px;' do
                      = image_tag("voucher/logo.png", :alt => "mmlodging", :style => "display:block; border:0; margin:0;", :width => "350")
                    %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                      %tbody
                        %tr
                          %td{:height => "4", :width => "4"}
                            %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                          %td{:bgcolor => "#FFFFFF", :colspan => "3", :rowspan => "3", :style => "padding:0 0 30px;"}
                            %p{:style => "margin: 30px 30px 10px; text-align:left; font-size:24px; line-height:30px; font-weight:bold; color:rgb(81, 163, 231);"}
                              = "Dear #{@checkout.first_name} #{@checkout.last_name},"
                            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :style => "margin-bottom: 15px", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td{:width => "30"}
                                    %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                            %p{:style => "margin:0; border-top:2px solid #e5e5e5; font-size:5px; line-height:5px; margin:0 30px 29px;"} &nbsp;
                            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      You can review your lodging stayed by visiting this link
                                %tr{:valign => "top"}
                                  %td{:align => "center"}
                                    = link_to "Review", property_reviews_url(@checkout.property, :booking_id => @checkout.booking_id), :style => " background: rgb(81, 163, 231); color: #ffffff; border: none; padding: 5px 15px; margin:0 0 30px 0; font-size:14px; font-weight: bold; line-height: 30px; text-decoration:none; width:190px; display:block;"
                                %tr{:valign => "top"}
                                  %td
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      If you have any technical difficulties while logging in, please do not hesitate to contact us. We are here to assist you in any way possible! Thank you again and we hope to see you soon.
                                    = image_tag("voucher/footer.png", :class => 'image img-footer', :height => "200", :src => "footer.png", :style => "margin-bottom: -50px margin-left: 0px", :width => "800")

app/views/contact_us/submit_contact_admin.text.erb
Dear Admin, 
The following was sent through the “Contact Us” function of the MMLodging 
webpage. 
First Name: <%= @first %>
Last Name: <%= @last %> 
E-Mail: <%= @email %> 
Message: 
<%= @message %>

-------------------------------------------- 
Kind Regards 

app/views/contact_us/submit_contact_user.text.erb
Dear Mr/Mrs/Ms: <%= @last %>, 
Thank you for contacting MMLodging. We are happy to assist you in your enquiries. 
A member of our customer service team will contact you as soon as possible. Please 
allow up to 48 hours for a response. 
We greatly appreciate your business. 
Sincerely, 
MMLodging

app/views/contact_us/submit_order_user.html.haml
%html
  %head
    %meta{:charset => "utf-8"}
      %title Your Booking Has Been Confirmed
      %link{:href => "http://fonts.googleapis.com/css?family=Varela+Round", :rel => "stylesheet", :type => "text/css"}

  %body{:style => "font-family: 'Varela Round', sans-serif; background-color:#f0f2ea; margin:0; padding:0; color:#333333;"}
    %table.force-row.container{:bgcolor => "#f0f2ea", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
      %tbody
        %tr
          %td{:style => "padding:40px 0;"}
            %table.force-row.container{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "800"}
              %tbody
                %tr
                  %td
                    = link_to root_url, :style => "display:block; width:800px; margin:0 auto 30px;" do
                      = image_tag("voucher/logo.png", :alt => "mmlodging", :style => "display:block; border:0; margin:0;", :width => "350")
                    %table.force-row.container{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                      %tbody
                        %tr
                          %td{:height => "4", :width => "4"}
                            %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                          %td{:bgcolor => "#FFFFFF", :colspan => "3", :rowspan => "3", :style => "padding:0 0 30px;"}
                            %p{:style => "margin: 30px 30px 10px; text-align:left; font-size:24px; line-height:30px; font-weight:bold; color:rgb(81, 163, 231);"}
                              = "Dear #{@checkout.first_name} #{@checkout.last_name},"
                            %table.force-row.container{:border => "0", :cellpadding => "0", :cellspacing => "0", :style => "margin-bottom: 15px", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td{:width => "30"}
                                    %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                            %p{:style => "margin:0; border-top:1px solid #e5e5e5; font-size:5px; line-height:5px; margin:0 30px 29px;"} &nbsp;
                            %table.force-row.container{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td
                                    %p{:style => "margin:0; margin:0 30px 30px; line-height: 30px"}
                                      = "Your booking already requested. this is your Booking ID: #{@checkout.booking_id}"
                                - if !@checkout.special.nil? || !@checkout.special.empty?
                                  %tr{:valign => "top"}
                                    %td
                                      %p{:style => "margin:0; margin:0 30px 30px; line-height: 30px"}
                                        %strong Special Request: 
                                        = @checkout.special
                                %tr{:valign => "top"}
                                  %td
                                    %p{:style => "margin:0; margin:0 30px 30px; line-height: 30px"}
                                      This is the list of your checkouts :
                                %table.table-content.force-row.container{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%", :style => 'padding: 20px;'}
                                  %tr{:valign => "top"}
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/hotel.png", :alt => 'hotel')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Lodging Name:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= @checkout.property.title
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/room-type.png", :alt => 'room type')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Room Type:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= @checkout.room.title
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/max-guesst.png", :alt => 'max guest')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Max Guests:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= pluralize(@checkout.room.guest, "guest")
                                  %tr
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/check-in.png", :alt => 'check in')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Check in
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= @checkout.check_in.strftime("%d %b %Y")
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/check-out.png", :alt => 'check out')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Check Out:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= @checkout.check_out.strftime("%d %b %Y")
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/price-night.png", :alt => 'price night')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Price/Night:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= number_to_currency(@checkout.per_night)
                                  %tr
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/time.png", :alt => 'check in')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Check In Time:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= pluralize(@checkout.property.check_in, "hour")
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/time.png", :alt => 'check out')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Check Out Time:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= pluralize(@checkout.property.check_out, 'hour')
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/tax.png", :alt => 'tax')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Tax:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= number_to_currency(@checkout.service + @checkout.government)
                                  %tr
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/rooms.png", :alt => 'rooms')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} No of Rooms:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= pluralize(@checkout.no_room, "room")
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/night.png", :alt => 'nights')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Night:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= pluralize(@checkout.nights, "night")
                                    %td{:style => 'border-bottom: 1px solid #DDD;padding-bottom: 15px;padding-top: 20px;padding-left: 10px;'}
                                      = image_tag("voucher/total-price.png", :alt => 'total price')
                                      %span{:style => 'color: rgb(81, 163, 231);font-size: 12px;margin-right: 10px;margin-left: 10px;'} Total Price:
                                      %span{:style => 'font-size: 12px;margin-right: 10px;margin-left: 10px;'}= number_to_currency(@checkout.total_cart)
                                
                                = image_tag("voucher/footer.png", :alt => 'footer', :class => 'image img-footer', :style => "margin-bottom: -50px margin-left: 0px", :width => "800")

app/views/contact_us/update_hotel_admin.text.erb
Hotel was update!
Name: <%= @hotel.title %>
City: <%= @hotel.city.name %>
User: <%= @current_user.email %>

Dear Admin, 
The following hotel has updated information concerning their establishment: 
Hotel Name: <%= @hotel.title %>
<%- if @hotel.property_type %>
Hotel Type: <%= @hotel.property_type %>
<%- end %>
<%- if @hotel.address %>
Hotel Address: <%= @hotel.address %>
<%- end %>
The following changes have successfully been made: 
Kind Regards 

app/views/contact_us/update_hotel_user.text.erb
Dear Valued Partner, 
You have successfully updated your information concerning your establishment. 
We wish you a pleasant day! 
Kind Regards, 
MMLodging

app/views/contact_us/user_sign_in.html.haml
%html
  %head
    %meta{:charset => "utf-8"}
      %title= "Your Account Already Confirmed"
      %link{:href => "http://fonts.googleapis.com/css?family=Varela+Round", :rel => "stylesheet", :type => "text/css"}
  %body{:style => "font-family: 'Varela Round', sans-serif; background-color:#f0f2ea; margin:0; padding:0; color:#333333;"}
    %table{:bgcolor => "#f0f2ea", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
      %tbody
        %tr
          %td{:style => "padding:40px 0;"}
            %table{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "800"}
              %tbody
                %tr
                  %td
                    = link_to root_url, :style => 'display:block; width:800px; margin:0 auto 30px;' do
                      = image_tag("voucher/logo.png", :alt => "mmlodging", :style => "display:block; border:0; margin:0;", :width => "350")
                    %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                      %tbody
                        %tr
                          %td{:height => "4", :width => "4"}
                            %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                          %td{:bgcolor => "#FFFFFF", :colspan => "3", :rowspan => "3", :style => "padding:0 0 30px;"}
                            %p{:style => "margin: 30px 30px 10px; text-align:left; font-size:24px; line-height:30px; font-weight:bold; color:rgb(81, 163, 231);"}
                              = "Dear #{@user.email},"
                            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :style => "margin-bottom: 15px", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td{:width => "30"}
                                    %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                            %p{:style => "margin:0; border-top:2px solid #e5e5e5; font-size:5px; line-height:5px; margin:0 30px 29px;"} &nbsp;
                            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 100px; line-height: 30px"}
                                      Your Account has been confirmed.
                                %tr{:valign => "top"}
                                  %td{:align => "center", :style => 'margin-top: 120px'}
                                %tr{:valign => "top"}
                                  %td{:style => "margin-top:150px;line-height:200px;"}
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      With Best Regards.
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      MMLODGING TEAM.
                                    = image_tag("voucher/footer.png", :class => 'image img-footer', :height => "200", :src => "footer.png", :style => "margin-bottom: -50px margin-left: 0px", :width => "800")

app/views/contact_us/user_sign_in_to_admin.html.haml
%html
  %head
    %meta{:charset => "utf-8"}
      %title= "New User Registered"
      %link{:href => "http://fonts.googleapis.com/css?family=Varela+Round", :rel => "stylesheet", :type => "text/css"}
  %body{:style => "font-family: 'Varela Round', sans-serif; background-color:#f0f2ea; margin:0; padding:0; color:#333333;"}
    %table{:bgcolor => "#f0f2ea", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
      %tbody
        %tr
          %td{:style => "padding:40px 0;"}
            %table{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "800"}
              %tbody
                %tr
                  %td
                    = link_to root_url, :style => 'display:block; width:800px; margin:0 auto 30px;' do
                      = image_tag("voucher/logo.png", :alt => "mmlodging", :style => "display:block; border:0; margin:0;", :width => "350")
                    %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                      %tbody
                        %tr
                          %td{:height => "4", :width => "4"}
                            %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                          %td{:bgcolor => "#FFFFFF", :colspan => "3", :rowspan => "3", :style => "padding:0 0 30px;"}
                            %p{:style => "margin: 30px 30px 10px; text-align:left; font-size:24px; line-height:30px; font-weight:bold; color:rgb(81, 163, 231);"}
                              = "Dear Administrator,"
                            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :style => "margin-bottom: 15px", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td{:width => "30"}
                                    %p{:style => "margin:0; font-size:1px; line-height:1px;"} &nbsp;
                            %p{:style => "margin:0; border-top:2px solid #e5e5e5; font-size:5px; line-height:5px; margin:0 30px 29px;"} &nbsp;
                            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                              %tbody
                                %tr{:valign => "top"}
                                  %td
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      = "User with email #{@user.email} has register to mmlodging."
                                %tr{:valign => "top"}
                                  %td{:align => "center", :style => 'margin-top: 120px'}
                                %tr{:valign => "top"}
                                  %td{:style => "margin-top:150px;line-height:200px;"}
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      Kind Regards.
                                    %p{:style => "margin:0; font-size:14px; margin:0 30px 30px; line-height: 30px"}
                                      MMLodging.
                                    = image_tag("voucher/footer.png", :class => 'image img-footer', :height => "200", :src => "footer.png", :style => "margin-bottom: -50px margin-left: 0px", :width => "800")